services:
  agentic-rag-api:
    build: .
    container_name: agentic-rag-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
